# **Kelompok 8:**
1. 1206210018_Winalda Risky Febriyanti
2. 1206230010_ Ikfan Putra Maesru Dwi Pradana
3. 1206230026_Aisya Mufidah Najwa
4. 1206230044_Mochammad Fery Ardiansyah

## Data Colection

In [ ]:
twitter_auth_token = '362abfd42037942d222c9d37478a2b3c8ae69c6e'

Blok ini melakukan instalasi Node.js, yang diperlukan untuk menjalankan tweet-harvest, sebuah tool berbasis Node.js untuk scraping data dari Twitter.

Langkah-langkahnya:
1. Update repository (apt-get update).
2. Pasang dependensi yang diperlukan (ca-certificates, curl, gnupg).
3. Menambahkan kunci GPG dan repository Node.js ke sistem.
4. Menginstal Node.js versi terbaru.

In [ ]:
!pip install pandas

!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1,372 kB]
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,533 kB]
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:14 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [57.9 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,235 kB]
Fetched 4,588 kB in 2s (2,330 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.20).
gnupg is already the newest version (2.2.27-3ubuntu2.1).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.
gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.18.3-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 31 not upgraded.
v20.18.3

**keywords**: List kata kunci yang digunakan dalam pencarian, berhubungan dengan kasus korupsi Pertamina.

**hashtags**: List hashtag yang relevan dengan topik yang akan diambil dari Twitter.

Menyusun format pencarian untuk tweet-harvest:
1. "query": Kata kunci atau hashtag yang
dicari.
2. since:2025-02-25 until:2025-03-12: Mencari tweet dalam rentang 25 Februari 2025 - 12 Maret 2025.
3. lang:id: Hanya mencari tweet dalam bahasa Indonesia.

Menjalankan perintah scraping menggunakan tweet-harvest melalui os.system().

Parameter:
1. npx -y tweet-harvest@2.6.1: Menjalankan tweet-harvest versi 2.6.1.
2. -o "{filename}": Menyimpan hasil dalam file CSV yang telah ditentukan.
3. -s "{search_query}": Menggunakan kata kunci yang telah dirancang sebelumnya.
4. --tab "LATEST": Mengambil tweet terbaru dari Twitter.
5. -l 1500: Mengambil maksimal 1500 tweet untuk setiap pencarian.
6. --token {twitter_auth_token}: Menggunakan token autentikasi untuk mengakses data Twitter.

In [ ]:
import os

keywords = [
    "Korupsi Pertamina", "Kasus Korupsi Pertamina", "Mafia Migas",
    "Direksi Pertamina", "Skandal Keuangan Pertamina", "KPK Pertamina",
    "Audit Pertamina", "BUMN korupsi", "Kasus suap Pertamina",
    "Komisaris Pertamina", "Investigasi KPK Pertamina", "Menteri BUMN korupsi"
]

hashtags = [
    "#KorupsiPertamina", "#MafiaMigas", "#BUMNBersih", "#SaveKPK",
    "#SkandalPertamina", "#AuditPertamina"
]

query_list = keywords + hashtags

for i, query in enumerate(query_list):
    filename = f'korupsi_pertamina_{i+1}.csv'
    search_query = f'"{query}" since:2025-02-25 until:2025-03-12 lang:id'

    print(f"Mulai crawling: {query}")

    os.system(f'npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_query}" --tab "LATEST" -l 1500 --token {twitter_auth_token}')

    print(f"Crawling selesai untuk: {query}, data tersimpan di {filename}")

print("Semua crawling selesai!")

Mulai crawling: #KorupsiPertamina
Crawling selesai untuk: #KorupsiPertamina, data tersimpan di korupsi_pertamina_1.csv
Mulai crawling: #MafiaMigas
Crawling selesai untuk: #MafiaMigas, data tersimpan di korupsi_pertamina_2.csv
Mulai crawling: #BUMNBersih
Crawling selesai untuk: #BUMNBersih, data tersimpan di korupsi_pertamina_3.csv
Mulai crawling: #SaveKPK
Crawling selesai untuk: #SaveKPK, data tersimpan di korupsi_pertamina_4.csv
Mulai crawling: #SkandalPertamina
Crawling selesai untuk: #SkandalPertamina, data tersimpan di korupsi_pertamina_5.csv
Mulai crawling: #AuditPertamina
Crawling selesai untuk: #AuditPertamina, data tersimpan di korupsi_pertamina_6.csv
Semua crawling selesai!

**Kesimpulan**

Block kode diatas digunakan untuk mekakukan scraping data dari platform X dengan menggunakan tweet-harvest berdasarkan kata kunci dan hastag yang dibutuhkan terkait kasus korupsi pertamina

## Data Understanding

Ini adalah contoh dataset yang didapat dari proses scrapping di atas: Click [Dataset](https://drive.google.com/drive/folders/1nikEPSsWf-CiPWDVvMAynd6WnV1JLG8O?usp=sharing)

Dataset ini berisi data tweet yang diperoleh dari pencarian dalam rentang waktu 25 Februari 2025 - 12 Maret 2025. Data ini mencakup berbagai informasi terkait tweet, seperti teks tweet, tanggal, jumlah like, reply, retweet, username, lokasi, dan URL tweet.

1. conversation_id_str	ID percakapan tweet yang menunjukkan jika tweet tersebut bagian dari sebuah thread.
2. created_at	Tanggal dan waktu tweet diposting dalam format UTC.
3. favorite_count	Jumlah like (favorit) pada tweet.
4. full_text	Isi lengkap dari tweet.
5. id_str	ID unik dari tweet.
6. image_url	URL gambar yang disertakan dalam tweet (jika ada).
7. in_reply_to_screen_name	Username yang dituju dalam reply (jika merupakan balasan).
8. lang	Bahasa yang digunakan dalam tweet.
9. location	Lokasi pengguna (jika tersedia).
10. quote_count	Jumlah tweet lain yang mengutip tweet ini.
11. reply_count	Jumlah balasan pada tweet.
12. retweet_count	Jumlah retweet yang diterima.
13. tweet_url	URL langsung menuju tweet di Twitter.
14. user_id_str	ID unik pengguna yang membuat tweet.
15. username	Nama pengguna (handle Twitter) dari akun yang memposting tweet.

In [ ]:
import pandas as pd
import numpy as np

### Contoh Data Yang didapatkan

In [ ]:
# Kata kunci = "Korupsi Pertamina"
df1 = pd.read_csv('/content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_1.csv')
df1

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1899823933031088195,Wed Mar 12 14:04:57 +0000 2025,0,korupsi tok jancok,1899823933031088195,NaN,NaN,in,2112 | he him,0,0,0,https://x.com/qfterdive/status/189982393303108...,1671156610218229761,qfterdive
1,1899698657429262778,Wed Mar 12 14:04:44 +0000 2025,0,@Syaifud30457221 @DokterTifa Tahu siapa yang k...,1899823880304525356,NaN,Syaifud30457221,in,NaN,0,0,0,https://x.com/JokoBangun7/status/1899823880304...,1455144866363498502,JokoBangun7
2,1899823744337723634,Wed Mar 12 14:04:12 +0000 2025,0,korupsi,1899823744337723634,NaN,NaN,in,Tanah Indah Kabupaten Sleman,0,0,0,https://x.com/aadityaaaaw/status/1899823744337...,1143436726527860737,aadityaaaaw
3,1899715872413151514,Wed Mar 12 14:03:43 +0000 2025,0,@GunRomli Atau Mungkin mereka Takut Ketahuan k...,1899823625227891081,NaN,GunRomli,in,NaN,0,0,0,https://x.com/Kahingking/status/18998236252278...,1670047549502410752,Kahingking
4,1899685896943010225,Wed Mar 12 14:03:21 +0000 2025,1,@mediaindonesia Cari panggung untuk menguak ko...,1899823529350324421,NaN,mediaindonesia,in,Keboen Anggur,0,0,0,https://x.com/M4M4D_C41303L/status/18998235293...,1816303493940142087,M4M4D_C41303L
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1510,1899675861672227093,Wed Mar 12 04:22:22 +0000 2025,1,@HeriM_paung Kasus korupsi itu sudah terjadi s...,1899677323429085407,NaN,HeriM_paung,in,Indonesia,0,0,0,https://x.com/DedynurPalakka/status/1899677323...,1003546165105704962,DedynurPalakka
1511,1899663185474666887,Wed Mar 12 04:22:16 +0000 2025,0,@dian_arifiya Negara kek gini korupsi gasi?,1899677295176302853,NaN,dian_arifiya,in,Bdg,0,0,0,https://x.com/dimasdimm_/status/18996772951763...,1212075417466621952,dimasdimm_
1512,1899677267242160439,Wed Mar 12 04:22:09 +0000 2025,1,*Buka X* *Scroll dikit* Berita korupsi *Scroll...,1899677267242160439,NaN,NaN,in,NaN,0,1,0,https://x.com/RandomBoyOnTwit/status/189967726...,1448337405463826438,RandomBoyOnTwit
1513,1899677266239692854,Wed Mar 12 04:22:09 +0000 2025,0,Babak Baru Sidang Korupsi PON XX Papua: Saling...,1899677266239692854,NaN,NaN,in,NaN,0,0,0,https://x.com/Korericom/status/189967726623969...,903230649045204993,Korericom
1514,1899636125502964150,Wed Mar 12 04:21:53 +0000 2025,1,@m_mirah Banyak kasus korupsi kebocoran uang n...,1899677202138144775,NaN,m_mirah,in,NaN,0,1,0,https://x.com/AngestikaD/status/18996772021381...,1468132871986565121,AngestikaD

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1515 entries, 0 to 1514
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      1515 non-null   int64
 1   created_at               1515 non-null   object
 2   favorite_count           1515 non-null   int64
 3   full_text                1515 non-null   object
 4   id_str                   1515 non-null   int64
 5   image_url                168 non-null    object
 6   in_reply_to_screen_name  931 non-null    object
 7   lang                     1515 non-null   object
 8   location                 702 non-null    object
 9   quote_count              1515 non-null   int64
 10  reply_count              1515 non-null   int64
 11  retweet_count            1515 non-null   int64
 12  tweet_url                1515 non-null   object
 13  user_id_str              1515 non-null   int64
 14  username                 1515 non-null   object
dtypes: int64(7), object(8)
memory usage: 177.7+ KB

In [ ]:
# Kata kunci = "Kasus Korupsi Pertamina"
df2 = pd.read_csv('/content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_2.csv')
df2

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1899652971224576189,Wed Mar 12 14:39:24 +0000 2025,0,@Heraloebss Kadang klo kasus gini yang kepikir...,1899832603596984728,NaN,Heraloebss,in,Manokwari,0,0,0,https://x.com/Sedang_di_isi/status/18998326035...,1077010295745179648,Sedang_di_isi
1,1899832571674145258,Wed Mar 12 14:39:16 +0000 2025,0,Kasus Mega Korupsi yang diungkap Kejagung bela...,1899832571674145258,https://pbs.twimg.com/ext_tw_video_thumb/18998...,NaN,in,NaN,0,0,0,https://x.com/_riverheaven/status/189983257167...,975389335775199232,_riverheaven
2,1899831047900287282,Wed Mar 12 14:38:58 +0000 2025,0,@Tiwisitiwul Itu kasus yang lama tenggelam,1899832493450436750,NaN,Tiwisitiwul,in,NaN,0,0,0,https://x.com/tit0tit0tit0/status/189983249345...,1228721436589559809,tit0tit0tit0
3,1899789227229147601,Wed Mar 12 14:38:55 +0000 2025,0,@luvmoinks Waktu kasus mbak ama mantannya itu ...,1899832481840537932,NaN,luvmoinks,in,she/her,0,0,0,https://x.com/huffleca/status/1899832481840537932,1148201094410981376,huffleca
4,1899832441449173231,Wed Mar 12 14:38:45 +0000 2025,0,Mvs saranin series dri mana aja yg 1 eps 1 kas...,1899832441449173231,NaN,NaN,in,NaN,0,0,0,https://x.com/moviemnfs/status/189983244144917...,1399254648,moviemnfs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1509,1899715786094018768,Wed Mar 12 10:47:31 +0000 2025,1,@sugarcanesuga @tanyarlfes Kim seonho kasus ap...,1899774247909888057,NaN,sugarcanesuga,in,NaN,0,1,0,https://x.com/aareumda/status/1899774247909888057,1507893979072790530,aareumda
1510,1899774217853559174,Wed Mar 12 10:47:24 +0000 2025,0,Senyum-senyum nulis buku kasus soalnya bocilku...,1899774217853559174,NaN,NaN,in,Palestine will be free 🇵🇸,0,1,0,https://x.com/crobitaa/status/1899774217853559174,1531540176832344064,crobitaa
1511,1899763023931449419,Wed Mar 12 10:47:05 +0000 2025,0,@sapahayo12345 itu cuman jokes kasus nimas adi...,1899774137612267754,NaN,sapahayo12345,in,🇮🇩she/her,0,1,0,https://x.com/luvmoinks/status/189977413761226...,1354647156049682434,luvmoinks
1512,1899292733497573667,Wed Mar 12 10:46:58 +0000 2025,0,@hasanizer @ardi_wm halo mas terus kasus ANAK ...,1899774111536103465,NaN,hasanizer,in,berachain,0,0,0,https://x.com/bruisedbadly/status/189977411153...,928974829629227008,bruisedbadly
1513,1899774031517077936,Wed Mar 12 10:46:39 +0000 2025,0,kasus menn,1899774031517077936,NaN,NaN,in,"asbunn, dumpss, homo.",0,0,0,https://x.com/ssweetlycake/status/189977403151...,1641979472038744065,ssweetlycake

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1514 entries, 0 to 1513
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      1514 non-null   int64
 1   created_at               1514 non-null   object
 2   favorite_count           1514 non-null   int64
 3   full_text                1514 non-null   object
 4   id_str                   1514 non-null   int64
 5   image_url                112 non-null    object
 6   in_reply_to_screen_name  786 non-null    object
 7   lang                     1514 non-null   object
 8   location                 758 non-null    object
 9   quote_count              1514 non-null   int64
 10  reply_count              1514 non-null   int64
 11  retweet_count            1514 non-null   int64
 12  tweet_url                1514 non-null   object
 13  user_id_str              1514 non-null   int64
 14  username                 1514 non-null   object
dtypes: int64(7), object(8)
memory usage: 177.6+ KB

In [ ]:
# Kata kunci = "Mafia Migas"
df3 = pd.read_csv('/content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_3.csv')
df3

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1899843917803086226,Wed Mar 12 15:24:22 +0000 2025,0,A deputada federal Alessandra Haber (MDB) afir...,1899843917803086226,https://pbs.twimg.com/media/Gl2Z-ZPWgAAbpr9.jpg,NaN,pt,"Rio de Janeiro, Brasil",0,0,0,https://x.com/N_Carvalheira/status/18998439178...,1089535657,N_Carvalheira
1,1899575569349538274,Wed Mar 12 15:24:21 +0000 2025,0,@desfemdazai Meio fora do assunto mas eu não m...,1899843915563319692,NaN,desfemdazai,pt,NaN,0,0,0,https://x.com/HertaWife/status/189984391556331...,1866917177443454976,HertaWife
2,1899800414846902509,Wed Mar 12 15:24:19 +0000 2025,0,@Matt_Bracken48 230 000 000 Khazaren Mafia dir...,1899843906361024955,NaN,Matt_Bracken48,in,NaN,0,0,0,https://x.com/bob161802/status/189984390636102...,1827795668091465728,bob161802
3,1899181198938689637,Wed Mar 12 15:24:17 +0000 2025,0,@HeninKristen @ActuFoot_ @RMCsport Froisser ?,1899843897901068680,NaN,HeninKristen,fr,"Paris, France",0,0,0,https://x.com/foot1666/status/1899843897901068680,1877421383421960193,foot1666
4,1899837229146492967,Wed Mar 12 15:24:16 +0000 2025,0,@mahagess na verdade é uma máfia a CBF é uma m...,1899843894524670175,NaN,mahagess,pt,"Santos, Brasil",0,0,0,https://x.com/DouglasBN21/status/1899843894524...,1226267055248285696,DouglasBN21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1499,1899822449132539946,Wed Mar 12 13:59:03 +0000 2025,0,Pengan main mafia nobar semuanyaa mau aku laku...,1899822449132539946,NaN,NaN,in,Jaxence𖹭,0,0,0,https://x.com/euphorynee/status/18998224491325...,1348201405832601602,euphorynee
1500,1899519390644584921,Wed Mar 12 13:59:02 +0000 2025,0,@hubdotxyz David Marcus. PayPal Mafia member s...,1899822445743481163,NaN,hubdotxyz,en,Macao,0,0,0,https://x.com/ToniSantanqecto/status/189982244...,1855550344690024448,ToniSantanqecto
1501,1899810098056196201,Wed Mar 12 13:58:57 +0000 2025,2,@Marr_1095 I am totally not a mafia heir tryin...,1899822425417601454,NaN,Marr_1095,en,NaN,0,1,0,https://x.com/MoonCatOmelet/status/18998224254...,992469855839379456,MoonCatOmelet
1502,1899335501187805510,Wed Mar 12 13:58:56 +0000 2025,0,@ElioMesones @JBCPERU Dirás de la mafia pritic...,1899822418761335218,NaN,ElioMesones,es,NaN,0,0,0,https://x.com/Pedro36965890/status/18998224187...,1608325943789080578,Pedro36965890
1503,1899603080431223097,Wed Mar 12 13:58:54 +0000 2025,1,@Ministryof_monk @stay_nameless_ @Mafia_Mel17 ...,1899822411006242832,NaN,Ministryof_monk,en,NaN,0,1,0,https://x.com/kpj_comp/status/1899822411006242832,171932400,kpj_comp

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1504 entries, 0 to 1503
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      1504 non-null   int64
 1   created_at               1504 non-null   object
 2   favorite_count           1504 non-null   int64
 3   full_text                1503 non-null   object
 4   id_str                   1504 non-null   int64
 5   image_url                202 non-null    object
 6   in_reply_to_screen_name  1065 non-null   object
 7   lang                     1504 non-null   object
 8   location                 838 non-null    object
 9   quote_count              1504 non-null   int64
 10  reply_count              1504 non-null   int64
 11  retweet_count            1504 non-null   int64
 12  tweet_url                1504 non-null   object
 13  user_id_str              1504 non-null   int64
 14  username                 1504 non-null   object
dtypes: int64(7), object(8)
memory usage: 176.4+ KB

In [ ]:
# Kata kunci = "Direksi Pertamina"
df4 = pd.read_csv('/content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_4.csv')
df4

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1899858422218318002,Wed Mar 12 16:22:00 +0000 2025,0,Tiba2 gw mikir sebenernya sampe suara bisa did...,1899858422218318002,NaN,NaN,in,happy with Minsung,0,1,0,https://x.com/finixfairytale/status/1899858422...,1504122620920229889,finixfairytale
1,1899830816282411366,Wed Mar 12 16:22:00 +0000 2025,0,@Piyusaja2 ya gk mungkinlah logikanya aja Diru...,1899858421584945238,NaN,Piyusaja2,in,NaN,0,0,0,https://x.com/BeeetheBoss/status/1899858421584...,1572114953343209472,BeeetheBoss
2,1899698016606629926,Wed Mar 12 15:32:52 +0000 2025,0,@doublepaijo @realfedinuril @prabowo Bang drpd...,1899846060195103002,NaN,doublepaijo,in,Unknown,0,0,0,https://x.com/BobFoster_/status/18998460601951...,1665269424662941696,BobFoster_
3,1899765390773010809,Wed Mar 12 15:29:54 +0000 2025,0,@Ary_PrasKe2 @riekediahp @2TRafiS1 @Anak__Ogi ...,1899845311721566253,NaN,Ary_PrasKe2,in,NaN,0,0,0,https://x.com/HarryPattyRM00/status/1899845311...,1864781185165201408,HarryPattyRM00
4,1899838631055081885,Wed Mar 12 15:03:21 +0000 2025,6,&gt;ga pernah produksi film selain jadi exec p...,1899838631055081885,https://pbs.twimg.com/media/Gl2UprIbYAAxbrR.png,NaN,in,In your phone,0,0,0,https://x.com/tilehopper/status/18998386310550...,1249662133916192768,tilehopper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1500,1895408179854594454,Fri Feb 28 09:38:19 +0000 2025,0,Ruwet kerjaan ruwet direksi rs ruwet penya neg...,1895408179854594454,NaN,NaN,in,NaN,0,1,0,https://x.com/aduhkepencetnih/status/189540817...,269303059,aduhkepencetnih
1501,1895130608562831588,Fri Feb 28 09:27:40 +0000 2025,4,@koganenohikari serombongan direksi doang itu ...,1895405499212009940,NaN,koganenohikari,in,Rent Free in Your Mind,0,2,0,https://x.com/MorphoMenelausX/status/189540549...,1397729807564111873,MorphoMenelausX
1502,1895330457145020431,Fri Feb 28 09:25:00 +0000 2025,0,@DedynurPalakka Ya hal menarik akrng gw isi be...,1895404829192974535,NaN,DedynurPalakka,in,NaN,0,0,0,https://x.com/RomyLestari/status/1895404829192...,1183152720342962176,RomyLestari
1503,1895043992208974055,Fri Feb 28 09:19:54 +0000 2025,0,@VIVAcoid Ganti semua komisaris dan direksi pe...,1895403544825798794,NaN,VIVAcoid,in,Jakarta,0,0,0,https://x.com/Djoe_Lid/status/1895403544825798794,1091767028904390656,Djoe_Lid
1504,1894925417900835236,Fri Feb 28 09:08:05 +0000 2025,0,@txtdrimedia Ni BUMN udah rugi mulu tapi gaji ...,1895400568514060322,NaN,txtdrimedia,in,NaN,0,0,0,https://x.com/goro2bojo/status/189540056851406...,1297647716936237057,goro2bojo

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1505 entries, 0 to 1504
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      1505 non-null   int64
 1   created_at               1505 non-null   object
 2   favorite_count           1505 non-null   int64
 3   full_text                1505 non-null   object
 4   id_str                   1505 non-null   int64
 5   image_url                231 non-null    object
 6   in_reply_to_screen_name  995 non-null    object
 7   lang                     1505 non-null   object
 8   location                 832 non-null    object
 9   quote_count              1505 non-null   int64
 10  reply_count              1505 non-null   int64
 11  retweet_count            1505 non-null   int64
 12  tweet_url                1505 non-null   object
 13  user_id_str              1505 non-null   int64
 14  username                 1505 non-null   object
dtypes: int64(7), object(8)
memory usage: 176.5+ KB

In [ ]:
# Kata kunci = "Skandal Keuangan Pertamina"
df5 = pd.read_csv('/content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_5.csv')
df5

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1899867263848898664,Wed Mar 12 16:57:08 +0000 2025,0,berdoa semoga usok ga kena skandal apa apa,1899867263848898664,NaN,NaN,in,NaN,0,0,0,https://x.com/pawspawsss/status/18998672638488...,1175190759311462400,pawspawsss
1,1899867187260572129,Wed Mar 12 16:56:49 +0000 2025,0,NGO Skandal für Merz immer Schlimmer! https://...,1899867187260572129,https://pbs.twimg.com/media/Gl2vIxTWQAATQLX.png,NaN,de,Rüsselsheim,0,0,0,https://x.com/PRESSECOP/status/189986718726057...,1695393591982424064,PRESSECOP
2,1899758289967100118,Wed Mar 12 16:56:42 +0000 2025,1,@michaldworczyk Skandal! Niemcy będę się zbroi...,1899867155274895506,NaN,michaldworczyk,pl,NaN,0,0,0,https://x.com/DziedzicPruskii/status/189986715...,1192443259261468672,DziedzicPruskii
3,1899862090619232465,Wed Mar 12 16:56:05 +0000 2025,0,@AndreasAndy3131 @Internette32171 @BBattmer @F...,1899867000199143769,NaN,AndreasAndy3131,de,"Düsseldorf, Germany",0,0,0,https://x.com/geek_blogger/status/189986700019...,205577765,geek_blogger
4,1899866952170168610,Wed Mar 12 16:55:53 +0000 2025,0,viral terbaru seleb tiktok silly hyper hijab v...,1899866952170168610,https://pbs.twimg.com/media/Gl2tJEOaAAA2JIO.jpg,NaN,in,Transdinyester,0,1,0,https://x.com/MaricellaC97542/status/189986695...,1884790354018287616,MaricellaC97542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1499,1899485291796480290,Tue Mar 11 21:27:15 +0000 2025,1,@luvmoinks dr awal emg mungkin tujuannya mau n...,1899572855291211914,NaN,luvmoinks,in,"kwu 24',UB",0,0,0,https://x.com/tatiuwwww/status/189957285529121...,1503639987102707712,tatiuwwww
1500,1899572189810069678,Tue Mar 11 21:26:14 +0000 2025,1,@NicoDziakson Skandal że liverporzokom nie gwi...,1899572598843019453,NaN,NicoDziakson,pl,NaN,0,0,0,https://x.com/maciejdurr/status/18995725988430...,1538723738065199104,maciejdurr
1501,1899571826478711010,Tue Mar 11 21:26:12 +0000 2025,0,@1223zip Duh kalo babang ichang sampe kena ska...,1899572591721148516,NaN,1223zip,in,back stage,0,0,0,https://x.com/nuttzilaa/status/189957259172114...,1083952111304400896,nuttzilaa
1502,1899572489446920287,Tue Mar 11 21:25:48 +0000 2025,0,Agak ikut pedih tiap liat berita saeron ni. Ni...,1899572489446920287,NaN,NaN,in,Hyping PLATONICFRIENDSHIP ONLY,0,1,0,https://x.com/rkiveshits/status/18995724894469...,1507675757018947586,rkiveshits
1503,1899357849890738178,Tue Mar 11 21:25:44 +0000 2025,3,@Martin_Sellner @MobiusPeter @CG_Romania Das i...,1899572474469130653,NaN,Martin_Sellner,de,Meck/Pom,0,0,0,https://x.com/MarkoKenzo/status/18995724744691...,1428457188075446272,MarkoKenzo

In [ ]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1504 entries, 0 to 1503
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      1504 non-null   int64
 1   created_at               1504 non-null   object
 2   favorite_count           1504 non-null   int64
 3   full_text                1504 non-null   object
 4   id_str                   1504 non-null   int64
 5   image_url                188 non-null    object
 6   in_reply_to_screen_name  785 non-null    object
 7   lang                     1504 non-null   object
 8   location                 783 non-null    object
 9   quote_count              1504 non-null   int64
 10  reply_count              1504 non-null   int64
 11  retweet_count            1504 non-null   int64
 12  tweet_url                1504 non-null   object
 13  user_id_str              1504 non-null   int64
 14  username                 1504 non-null   object
dtypes: int64(7), object(8)
memory usage: 176.4+ KB

## Merge

In [1]:
import pandas as pd

total_data = 0

for i in range(1, 15):
    filename = f'/content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_{i}.csv'
    try:
        df = pd.read_csv(filename)
        jumlah_baris = len(df)
        print(f'Jumlah data di {filename}: {jumlah_baris}')
        total_data += jumlah_baris
    except pd.errors.EmptyDataError:
        print(f'File {filename} is empty or unreadable. Skipping...')

print(f'\nTotal jumlah data dari seluruh dataset: {total_data}')

Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_1.csv: 1515
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_2.csv: 1514
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_3.csv: 1504
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_4.csv: 1505
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_5.csv: 1504
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_6.csv: 1514
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_7.csv: 168
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_8.csv: 1486
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_9.csv: 1507
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_10.csv: 388
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_11.csv: 16
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_12.csv: 21
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_13.csv: 2
Jumlah data di /content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_14.csv: 1

Total jumlah data dari seluruh dataset: 12645

In [2]:
import pandas as pd
df_main = pd.concat([pd.read_csv(f'/content/drive/MyDrive/MAKUL/SNA/Dataset/korupsi_pertamina_{i}.csv') for i in range(1, 15)])

In [3]:
df_main.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1899823933031088195,Wed Mar 12 14:04:57 +0000 2025,0,korupsi tok jancok,1899823933031088195,NaN,NaN,in,2112 | he him,0,0,0,https://x.com/qfterdive/status/189982393303108...,1671156610218229761,qfterdive
1,1899698657429262778,Wed Mar 12 14:04:44 +0000 2025,0,@Syaifud30457221 @DokterTifa Tahu siapa yang k...,1899823880304525356,NaN,Syaifud30457221,in,NaN,0,0,0,https://x.com/JokoBangun7/status/1899823880304...,1455144866363498502,JokoBangun7
2,1899823744337723634,Wed Mar 12 14:04:12 +0000 2025,0,korupsi,1899823744337723634,NaN,NaN,in,Tanah Indah Kabupaten Sleman,0,0,0,https://x.com/aadityaaaaw/status/1899823744337...,1143436726527860737,aadityaaaaw
3,1899715872413151514,Wed Mar 12 14:03:43 +0000 2025,0,@GunRomli Atau Mungkin mereka Takut Ketahuan k...,1899823625227891081,NaN,GunRomli,in,NaN,0,0,0,https://x.com/Kahingking/status/18998236252278...,1670047549502410752,Kahingking
4,1899685896943010225,Wed Mar 12 14:03:21 +0000 2025,1,@mediaindonesia Cari panggung untuk menguak ko...,1899823529350324421,NaN,mediaindonesia,in,Keboen Anggur,0,0,0,https://x.com/M4M4D_C41303L/status/18998235293...,1816303493940142087,M4M4D_C41303L

In [4]:
df_main.to_csv('korupsi_pertamina_merge.csv', index=False)

In [5]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12645 entries, 0 to 0
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      12645 non-null  int64
 1   created_at               12645 non-null  object
 2   favorite_count           12645 non-null  int64
 3   full_text                12644 non-null  object
 4   id_str                   12645 non-null  int64
 5   image_url                2142 non-null   object
 6   in_reply_to_screen_name  7286 non-null   object
 7   lang                     12645 non-null  object
 8   location                 6391 non-null   object
 9   quote_count              12645 non-null  int64
 10  reply_count              12645 non-null  int64
 11  retweet_count            12645 non-null  int64
 12  tweet_url                12645 non-null  object
 13  user_id_str              12645 non-null  int64
 14  username                 12645 non-null  object
dtypes: int64(7), object(8)
memory usage: 2.0+ MB

In [6]:
len(df_main)

12645

In [8]:
edges = df_main[df_main['in_reply_to_screen_name'].notna()][['username', 'in_reply_to_screen_name']]

edges.columns = ['Source', 'Target']

edges.to_csv('korupsi_edges.csv', index=False)

print("Edge list berhasil disimpan sebagai korupsi_edges.csv")

Edge list berhasil disimpan sebagai korupsi_edges.csv